### ISSUE TITLE
Answers are choosed automatically

### ISSUE THREAD

**Issue by ani27** [the-dagger/lEarnit#9]
These are the bugs which I found very annoying. They are on the quiz activity. After every quiz, even though I had not answer any question, the last page will show that I answered I got 9 out of 10 Questions right.
![screenshot_20161206-165719](https://cloud.githubusercontent.com/assets/10931958/20924180/3c434d68-bbd6-11e6-82c4-6b93bdbb8b91.png)

Also I can not leave the activity when talking the quiz.
![screenshot_20161206-165928](https://cloud.githubusercontent.com/assets/10931958/20924181/3cc30a9e-bbd6-11e6-840e-687d57348c44.png)

Also if I select an option and proceed further, after some time the question appears with marked option. There must be a bug in adapter.

Also the floating button image is not right and button to skip question must be there.

I would like to work on these issues. Let me know if you have some ideas

**Comment by the-dagger** [comment]
Hey, thanks for reporting these issues.
I didn't notice the bug which shows 9/10 questions correct at all times, so yeah you can go ahead and fix it.

The questions coming with their answers selected is a known bug and you can work on it.

Technically, if you don't select any question, pressing the fab should move on to the next question.

You can not leave the quizActivity by pressing the back button and that is intentional as we require the student to complete a single module in one go.

If you send Pull request for this, please be sure to send separate PRs for separate points mentioned above.

Cheers.

**Comment by ani27** [comment]
@the-dagger  Ok, on it
